#pragma once

#define BSS_MOUSE_BUTTON_1         0
#define BSS_MOUSE_BUTTON_2         1
#define BSS_MOUSE_BUTTON_3         2
#define BSS_MOUSE_BUTTON_4         3
#define BSS_MOUSE_BUTTON_5         4
#define BSS_MOUSE_BUTTON_6         5
#define BSS_MOUSE_BUTTON_7         6
#define BSS_MOUSE_BUTTON_8         7
#define BSS_MOUSE_BUTTON_LAST      BSS_MOUSE_BUTTON_8
#define BSS_MOUSE_BUTTON_LEFT      BSS_MOUSE_BUTTON_1
#define BSS_MOUSE_BUTTON_RIGHT     BSS_MOUSE_BUTTON_2
#define BSS_MOUSE_BUTTON_MIDDLE    BSS_MOUSE_BUTTON_3